name: Build

env:
  base64-keystore: ${{ secrets.BASE64_KEYSTORE }}
  keystore: keystore
  keystore-location: android/keystore
  keystore-properties: android/keystore.properties
  release-key-alias: ${{ secrets.RELEASE_KEY_ALIAS }}
  release-key-password: ${{ secrets.RELEASE_KEY_PASSWORD }}
  release-store-password: ${{ secrets.RELEASE_STORE_PASSWORD }}
  build-properties: android/build.properties
  application-id: ${{ secrets.APP_ID }}
  compile-sdk: 33
  min-sdk: 21
  target-sdk: 33
  version-code: 1
  version-name: 1.0.0
  apk-path: app/build/outputs/apk/release
  apk-name: ${{ vars.APK_NAME }}-${{ github.run_number }}.apk
  slack-token: ${{ secrets.SLACK_TOKEN }}
  slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
  slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependency
        run: yarn install
      - run: sudo chmod +x android/gradlew
        shell: bash
      - run: echo ${{ env.base64-keystore }} | base64 -d > ${{ env.keystore-location }}
        shell: bash
      - run: |
          echo "releaseKeyAlias=${{ env.release-key-alias }}" > ${{ env.keystore-properties }}
          echo "releaseKeyPassword=${{ env.release-key-password }}" >> ${{ env.keystore-properties }}
          echo "releaseKeyStore=${{ env.keystore }}" >> ${{ env.keystore-properties }}
          echo "releaseStorePassword=${{ env.release-store-password }}" >> ${{ env.keystore-properties }}
        shell: bash
      - run: |
          echo applicationId=${{ env.application-id }} > ${{ env.build-properties }}
          echo compileSdk=${{ env.compile-sdk }} >> ${{ env.build-properties }}
          echo minSdk=${{ env.min-sdk }} >> ${{ env.build-properties }}
          echo targetSdk=${{ env.target-sdk }} >> ${{ env.build-properties }}
          echo versionCode=${{ env.version-code }} >> ${{ env.build-properties }}
          echo versionName=${{ env.version-name }} >> ${{ env.build-properties }}
        shell: bash
      - run: |
          cd android
          ./gradlew assembleRelease
        shell: bash
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,ref # repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ env.slack-webhook-url }}
        if: always()
      - name: Change File Name
        run: |
          mv android/${{ env.apk-path }}/app-release.apk android/${{ env.apk-path }}/${{ env.apk-name }}
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.apk-name }}
          path: android/${{ env.apk-path }}/*.apk
      - name: Slack Upload Artifacts
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ env.slack-token }}
          channel_id: ${{ env.slack-channel-id }}
          file_path: 'android/${{ env.apk-path }}/${{ env.apk-name }}'