name: Build

env:
  JAVA_DISTRIBUTION: corretto
  JAVA_VERSION: 17
  COMPILE_SDK: 33
  MIN_SDK: 21
  TARGET_SDK: 33
  VERSION_CODE: ${{ github.run_number }}
  VERSION_NAME: 1.0.0

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SunChulBaek/build_android@v1
        with:
          build-react-native: true # for React Native
          android-home: "android" # for React Native
          java-distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          base64-keystore: ${{ secrets.BASE64_KEYSTORE }}
          release-key-alias: ${{ secrets.RELEASE_KEY_ALIAS }}
          release-key-password: ${{ secrets.RELEASE_KEY_PASSWORD }}
          release-store-password: ${{ secrets.RELEASE_STORE_PASSWORD }}
          application-id: ${{ secrets.APP_ID }}
          compile-sdk: ${{ env.COMPILE_SDK }}
          min-sdk: ${{ env.MIN_SDK }}
          target-sdk: ${{ env.TARGET_SDK }}
          version-code: ${{ env.VERSION_CODE }}
          version-name: ${{ env.VERSION_NAME }}
          artifact-name: "${{ vars.APK_NAME }}-${{ env.VERSION_CODE }}"
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}